#!/bin/bash

## chkrootkit es un lanzador para el escáner de rootkits chkrootkit, ayudando a
## detectar posibles compromisos de seguridad en el sistema.

help() {
    echo
    echo Lanzador para chkrootkit
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## chkrootkit"
echo
chkrootkit

