#!/bin/bash

## docker proporciona un estado rápido de los contenedores Docker en ejecución,
## facilitando la gestión y monitoreo de entornos contenerizados.

help() {
    echo
    echo Mostrar estado de docker.
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## docker stats --no-stream"
echo

docker stats --no-stream

