#!/bin/bash

## dokku muestra el estado de las aplicaciones desplegadas con Dokku,
## ofreciendo una visión general de tus despliegues en la nube.

help() {
    echo
    echo Mostrar estado de dokku.
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## dokku logs:failed"
echo

dokku logs:failed

# echo
# echo dokku
# echo
#
# echo "### dokku docker-options:report"
# dokku docker-options:report

