#!/bin/bash

## fail2ban reporta el estado del servicio fail2ban, incluyendo IPs bloqueadas
## por intentos de intrusión, para mantener la seguridad del servidor.

help() {
    echo
    echo Mostar estado de fail2ban.
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## Fail2Ban"

echo
echo "### fail2ban-client status"
echo

fail2ban-client status

echo
echo "### Status jails"
echo

for x in `fail2ban-client status | grep list | cut -d: -f2 | tr -d \,` ; do fail2ban-client status $x  ; done

echo
echo "### Numero de veces que se han bloqueado las IPs"
echo

zgrep -h "Ban " /var/log/fail2ban.log* | awk '{print $NF}' | sort | uniq -c | sort -nr | tee /tmp/ips_bloqueadas.txt

dn=`dirname "$0"`

${dn}/whois_list /tmp/ips_bloqueadas.txt

