#!/bin/bash

## firewall muestra el estado actual del firewall iptables, permitiéndote
## verificar las reglas de seguridad activas en el sistema.

help() {
    echo
    echo Mostrar estado del firewall.
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## IPs bloqueadas"
echo

echo "### iptables -L -n --line-numbers | grep REJECT"
echo

iptables -L -n --line-numbers | grep REJECT

#  echo
#  echo "### Reglas del cortafuegos"
#  echo
#
#  sudo iptables -L -n --line-numbers
