#!/bin/bash

## logcheck analiza los logs del sistema en busca de eventos inusuales,
## enviando reportes por email para alertas de seguridad.

help() {
    echo
    echo Mostrar estado de logcheck.
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## LogCheck"
echo

echo "### sudo -u logcheck logcheck -o -t"
echo
sudo -u logcheck logcheck -o -t

