#!/bin/bash

## lynis ejecuta una auditoría completa de seguridad del sistema usando Lynis,
## proporcionando recomendaciones para mejorar la protección.

help() {
    echo
    echo Consejos de seguridad para nuestro servidor.
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## lynis audit system"
echo
lynis audit system

