#!/bin/bash

## @file git_list_file_status
## @brief Listado de ficheros añadidos o modificados.

gitListFileStatus() {
    git status | grep '\.php' | cut -d: -f2 | sed 's/.* //g' | sed 's/.*\t//g'
}

gitListFileStatus
