#!/bin/bash

## Verificar estado de proyectos con git.
##
## Útil para verificar si tenemos algún cambio sin commitear en alguno de nuestros proyectos.

help() { doxygen2help "$0"; }
[[ "$1" == "-h" || "$1" == "--help" ]] && { help ; exit ; }

# Listado de proyectos
FILE_CONFIG=$HOME/.config/magscripts/magGitStatusAll

if [ -f "$FILE_CONFIG" ]; then
	LISTA_PROYECTOS=$(cat "$FILE_CONFIG")
else
	echo
	echo "$(basename "$0")"
	echo
	echo "Gestionar repositorios git"
	echo
	echo "Es necesario definir una lista de proyectos o carpetas de proyectos en el fichero: "
	echo "$FILE_CONFIG"
	echo
	echo "Un proyecto por linea"
	exit
fi

gitStatusShow() {

	if echo $* | grep '"git push' >/dev/null; then
		return 1
	fi
	if echo $* | grep '"git add' >/dev/null; then
		# echo -en "$*"
		return 2
	fi
	return 0

}

gitCheckStatus() {
	if gitStatusShow "$(git status)"; then
		echo
		pwd
		pwd | sed 's/./-/g'
		echo
		git status
	fi
}

gitstatusall() {

	for x in $*; do
		if [[ -d "$x" ]]; then
			cd "$x"
			if [ -e .git ]; then
				gitCheckStatus "$x"
				cd ../
			else
				echo "$x no es un repositorio git"
				cd ../
			fi
		else
			echo "$x no es un directorio"
		fi
	done
}

gitstatusall $LISTA_PROYECTOS
