#!/bin/bash

## @file
## @brief Mostrar lista de los ficheros añadidos o modificados en un repositorio Git.

listAddOrModifiedFiles() {
    git status --porcelain | grep -E '^[AM?]' | awk '{print $2}'
}

listAddOrModifiedFiles
