#!/bin/bash

## magGitCambiosRealizados lista todos los commits realizados en un repositorio
## Git, proporcionando un historial completo de los cambios para seguimiento y
## auditoría.

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

git log --graph --pretty=format:'%Cblue%h%Creset -%C(yellow)%d%Creset %s - %C(yellow)%aN%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative
