#!/bin/bash

## @file ctags_python
##
## @brief ctags para proyectos en python
##
## Generar archivo de ctags para proyecto en python, sobre el directorio donde estamos situados
##
## dependencias: ctags-exuberant
##
## @author   Eduardo Magrané
##
## @internal
##
##       web  http://www.lesolivex.com
##
##      mail  edu.lesolivex.com
##
## Copyright  Copyright (c) 2011, Eduardo Magrané
##
## This source code is released for free distribution under the terms of the
## GNU General Public License as published by the Free Software Foundation.

# --langmap=python:.py \

ctags-exuberant \
--exclude="\.git" \
--exclude="doc" \
--exclude="docs" \
--exclude="ext" \
--totals=yes \
--python-kinds=cfi \
--languages=python \
--tag-relative=yes \
--recurse
