#!/bin/bash

## @file comprobar_conexion
## @brief Testeamos conexión a internet hasta tener resultado positivo.
##
## Una vez detectada la vuelta de internet se lanzara reproductor.

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

limite=1000                              ##< Limite de intentos

echo -n "Comprobando conexión a internet "

for x in `seq 1 $limite` ; do

   echo -n .

   ping -c 3 www.google.com 2>/dev/null

   if [ $? = 0 ] ; then

      echo "Con conexión"
      notify-send "Conexión a internet" "restablecida"
      exit

   else
      sleep 5s
   fi

done
