#!/bin/bash

#URL="http://www.google.com/search?output=googleabout&q="
URL="https://duckduckgo.com/lite/?kp=-1&q="

NAVEGADOR="xdg-open"
NAVEGADOR="x-www-browser "

# Si no tenemos parámetros abrimos una ventana con lo que tengamos en el portapapeles

if [ $# -gt 0 ] ; then 

   for x in $* ; do
      URL="${URL}${x}+"
   done

else

   CONTENIDO="`xclip -o 2> /dev/null`"
   pp="`zenity --entry --entry-text=\"$CONTENIDO\"`"
   [[ "$?" != "0" ]] && echo 'Cancelado' && exit
   [[ "$pp" = "" ]] && echo 'Nada que buscar' && exit
   for x in $pp ; do
      URL="${URL}${x}+"
   done

fi

URL="${URL}&start=0&ie=utf-8&oe=utf-8&client=firefox&rls=org.mozilla:es-ES:unofficial"

if [ "$DISPLAY" = "" ] ; then
   links $URL 
else
   $NAVEGADOR $URL &
fi
