#!/bin/bash 

## @file informacion_ordenador
## 
## @brief Presentar por pantalla la información relevante del ordenador
## 
## Nos permite con un solo comando tener un informe de las características del hardware del ordenador
## 
## dependencias: dmidecode lspci fdisk
## 
## @author   Eduardo Magrané
## 
## @internal
##
##       web  http://www.lesolivex.com
##
##      mail  edu.lesolivex.com
##
##  Revision  SVN $Id: $
##
## Copyright  Copyright (c) 2011, Eduardo Magrané
## 
## This source code is released for free distribution under the terms of the
## GNU General Public License as published by the Free Software Foundation.

echo
echo Network
echo -------
echo

echo Hostname: $(cat /etc/hostname)
echo IP interna: $(hostname -I)
echo IP externa: $(curl -s ipecho.net/plain;echo)
echo IP_ETH0: $(ifconfig eth0 | grep inet | grep -v inet6 | cut -d ":" -f 2 | cut -d " " -f 1)
echo MAC_ETH0: $(ifconfig eth0 | sed -n '1p' | awk '{print $5}')
echo IP_WLAN0: $(ifconfig wlan0 | grep inet | grep -v inet6 | cut -d ":" -f 2 | cut -d " " -f 1)
echo MAC_WLAN0: $(ifconfig wlan0 | sed -n '1p' | awk '{print $5}')
echo PROXY_GATEWAY: $(route -n | sed -n '3p' | awk '{print $2}')
echo DOMINIO: $(cat /etc/resolv.conf | sed '2 d' | grep search | sed -n '1p' | awk '{print $2}') 
echo IP_SERVIDOR_DNS: $(cat /etc/resolv.conf | sed '1 d' | awk '{print $2}')
echo
who>/tmp/who ; echo -e "Usuarios conectados al Host :"  && echo "" && echo "Usuarios Puertos      Fecha      Hora  Pantalla" ; echo "*************************************************************************" && cat /tmp/who 
echo
echo USUARIOS_CONECTADOS: $(who | awk '{print $1}')
echo USER_ONLINE1: $(who | awk '{print $1}' ; echo $USER_ONLINE1 | wc -w)
echo USER_ONLINE2: $(top -n 1 -b | grep "load average:" | awk '{print $6}')

