#!/bin/bash

## magVerIp muestra tu dirección IP actual de manera rápida, útil para
## configuraciones de red o conexiones remotas.

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

curl -s ipecho.net/plain;echo
curl -4 ifconfig.io

