#!/bin/bash

#/**
# * cmpdir - juanayup@gmail.com, 2007, GPLv2
# *
# * cmpdir <dir1> <dir2>
# *
# * @todo Si los directorios vienen sin '/' al final hay que añadirla
# */

FILE="$HOME/`basename "$0"`.lista"
SRC="$1"
DST="$2"

comparar() {

   linea="$1"
   echo
   echo "LINEA: $linea"
   echo
   read -p "Comparar archivos: (s/n)" -n 1 -s OPCION < /dev/tty
   if [ "$OPCION" = "s" ] ; then gvimdiff `echo $linea | awk -v FS=' ' '{print $1 " " $2}'` ; fi
}

if [ "$1" == "archivo" ] ; then

   while read linea
   do
      comparar "$linea"
   done < "$FILE"

   exit
fi

[ -z "$2" ] && { echo "Usage: $SELF <dir1> <dir2>"; exit 0; }

(cd "$SRC";find -type f)|while read i;do cmp "${SRC}$i" "${DST}$i"; done | tee "$FILE"

#cat "$FILE" | grep distintos | awk -v FS=' ' '{printf "%s %s" $1 $2}'

