#!/bin/bash

## Transformar una imagen a formato jpg con la anchura o altura especificada
##
## @todo Las imágenes transformadas se guardan en el mismo directorio que las originales, estaría bien poder elegir un directorio diferente"
##
## dependencias: convert zenity

help() { doxygen2help "$0"; }
[[ "$1" == "-h" || "$1" == "--help" ]] && { help ; exit ; }

# Si se lanza el programa para saber si debe publicarse en la web
# contestamos y salimos
[[ "$1" = "--publico" ]] &&  echo 'SI' && exit 0

quality="70%"

# Si tenemos fichero de configuración recogemos lo insertamos
[[ -e "$var_fich_conf" ]] && source $var_fich_conf

while [ -n "$1" ] ; do

   case "$1" in

      -h|-help|--help) help ; exit ;;
      *) break ;;

   esac

done

modificar_anchura=0
modificar_altura=0

if [ "$1" = "" ] ; then
   # Escoger imágenes
   imagenes="$(zenity  --title="Selecciona una imagen" --file-selection --multiple )"
   s=''
   DIFS="$IFS" ; IFS=$'\|'
   for f in $imagenes ; do
      s="$s \"$f\""
   done
   IFS="$DIFS"
   eval "set - $s"
fi

if [ -z "$1" ] ; then
   echo "Sin imágenes"
   exit
else
   echo Imágenes:
   DIFS="$IFS" ; IFS=$'\|'
   for f in $@ ; do
    echo "- $f"
   done
   IFS="$DIFS"
fi

if [ "$DISPLAY" != "" ] ; then
   SALIDA=$(zenity --list --title "Convirtiendo imágenes" --text "Encoje una opción" --column "Opciones" 'No modificar tamaño' 'Modificar por altura' 'Modificar por Anchura')
   echo $SALIDA
   if [ "$SALIDA" == "Modificar por Anchura" ] || [ "$SALIDA" == "Modificar por Anchura|Modificar por Anchura" ] ; then
      anchura=$(zenity  --title "Anchura" --entry --text "Anchura en pixeles")
      [[ "$anchura" != "" ]] && modificar_anchura=1
   elif [ "$SALIDA" = "Modificar por altura" ] || [ "$SALIDA" == "Modificar por altura|Modificar por altura" ] ; then
      altura=$(zenity  --title "Altura" --entry --text "Altura en pixeles")
      [[ "$altura" != "" ]] && modificar_altura=1
   else
       exit
   fi
fi

# convertir imágenes a formato jpg

DIFS="$IFS"
IFS=$'\n'
for f in $@ ; do
	echo -e "\nConvirtiendo: " "$1"
   # Eliminamos extensión
	extension=$(echo $f | awk -v FS='.' '{print $(NF)}')
	echo $extension
	cmd="awk -v FS='.${extension}' '{print \$1}'"
	f2="$(echo $f | eval $cmd)"

	echo -e "a $f2-peque.jpg"
   if [ $modificar_anchura = 1 ] ; then
     echo Modificar por anchura: $anchura
     cmd='convert -quality $quality -geometry ${anchura} "$f" "${f2}${sufijo}_an${anchura}.jpg"'
   elif [ $modificar_altura = 1 ] ; then
     echo Modificar por altura: $altura
      cmd='convert -quality $quality -geometry x${altura} "$f" "${f2}${sufijo}_al${altura}.jpg"'
   else
     echo Solo convertimos a jpg
      cmd='convert "$f" "${f2}${sufijo}-convert.jpg"'
   fi

   if [ "$DISPLAY" = "" ] ; then
      eval $cmd
   else
      eval $cmd | zenity --progress --auto-close
   fi
	shift 1
done
IFS="$DIFS"

