#!/bin/bash

## @file ctags_python
##
## @brief ctags para proyectos en python
##
## Generar archivo de ctags para proyecto en python, sobre el directorio donde estamos situados
##
## dependencias: ctags-exuberant
##
## @author   Eduardo Magrané
##
## @internal
##
##       web  http://www.lesolivex.com
##
##      mail  edu.lesolivex.com
##
## Copyright  Copyright (c) 2011, Eduardo Magrané
##
## This source code is released for free distribution under the terms of the
## GNU General Public License as published by the Free Software Foundation.

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

dir=`dirname "$0"`
# --options=${dir}/vue.ctags \

ctags-exuberant \
--exclude="node_modules" \
--exclude="\.git" \
--exclude="doc" \
--exclude="docs" \
--totals=yes \
--tag-relative=yes \
--recurse \
--langdef=vue \
--langmap=vue:.vue \
--regex-vue='/^ {2}((name|"name")[^,]*)/\1/p,property/{scope=ref}' \
--regex-vue='/^ {2}((data) \(|("data"):|(data):)/data/p,property/{scope=set}' \
$@
