#!/bin/bash

## magBuscarEnlacesRotos escanea tu sitio web para detectar enlaces rotos,
## generando un reporte detallado que te ayuda a mantener la integridad y
## usabilidad de tu página web.
##
## Uso: magBuscarEnlacesRotos [url] [report file]

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

url=${1:-$mt_url_servidor}
file=${2:-/tmp/enlaces_rotos.txt}

if [[ -z $url ]] ; then
   echo "Error: Debe definirse la url."
   exit 1
fi

cmd="wget --spider -r -l 1 -nd -w 0 --progress=bar:force:noscroll --show-progress -o $file $url"

echo
echo url: "$url"
echo
echo comando: "$cmd"
echo

$cmd

echo
echo Archivo final: "$file"
echo
xdg-open "$file"
