#!/bin/bash

## @file buscar_enlaces_rotos
## @brief Comprobar enlaces rotos

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

## Error
function  error_enlaces() {
   echo
   echo uso: `basename $0` [url] [archivo final]
   echo
   if [ ! -z "$1" ] ; then
     echo
     echo -e "$1"
     echo
   fi
   exit 1
}

url=${1:-$mt_url_servidor}
terminal=${mt_miniterminal:-$TERM}
file=${2:-/tmp/enlaces_rotos.txt}

[[ -z $url ]] && error_enlaces "Debe definirse la url de destino"

cmd="wget --spider --no-check-certificate --no-parent -r  $url"

echo
echo url: $url
echo
echo comando: $cmd
echo

$cmd | tee -a $file

echo
echo Archivo final: $file
echo

mkdir /tmp/$$.lynx
cd /tmp/$$.lynx
# lynx -traversal $url > /dev/null
lynx -traversal http://$url
count=0;
sort -u reject.dat > links.txt
while read link;
do
output=`curl -I $link -s | grep "HTTP/.*OK"`;
if [[ -z $output ]];
then
echo $link;
let count++
fi
done < links.txt
if [ $count -eq 0 ] ; then
   echo
   echo Sin enlaces rotos
   echo
else
   echo
   echo $count enlaces rotos
   echo
fi

read
