#!/bin/bash

## @file comprobar_web
## @brief Hacer una comprobación para ver si la página está funcionando.
##
## Referencia:
## http://www.linuxhispano.net/2013/02/19/monitorizar-servidor-web-para-ver-si-esta-caido-o-no-de-forma-automatica/

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

if [ -z "$1" ] ; then
    echo
    echo Es necesario la url para poder ser analizada
    echo
    tecla
    exit 1
else
   url="$1"
fi

response=$(curl -s -I -L $url | grep HTTP);

status=${response#* };
status=${status:0:3};

if [ "$status" != "200" ]
then
   # acciones a efectuar
   echo "ERROR: $url"
   exit 1
fi
