#!/bin/bash

## @file magLastModifiedFiles
##
## @brief listamos los últimos archivos que han sido modificados
##
## Por defecto se muestran los archivos modificados en las últimas 24 horas
## del directorio actual.
##
## Opciones:
## <pre>
## --help | -h              Pantalla de ayuda
## </pre>

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

## Directorio a consultar.
dir="./"

## Mostrar ayuda

while [ -n "$1" ] ; do

   case "$1" in

      -h|-help|--help) help ; exit ;;
      --dependencias|-d) comprobar_dependencias ; exit ;;
      *) dir="$1" ; break ;;

   esac

done

## Comando
## 24h
comando_ultimos_modificados="find '$dir' -type f -mtime 0 | grep -v '.swp' | grep -v 'log/' | grep -v '.git' | sed 's/\.\///' | sed 's/^\.//'"
## 30min
# comando_ultimos_modificados="find '$dir' -type f -mmin -30 | grep -v '.swp' | grep -v 'log/' | grep -v '.git' | sed 's/\.\///' | sed 's/^\.//'"

echo Buscar las últimas 24 horas
echo $comando_ultimos_modificados
echo
eval "$comando_ultimos_modificados"
