#!/bin/bash

## magLastModifiedFiles te muestra una lista de los archivos modificados
## recientemente en un directorio, ideal para rastrear cambios en proyectos de
## desarrollo o mantener un registro de actividades recientes.
##
## Por defecto se muestran los archivos modificados en las últimas 24 horas
## del directorio actual.
##
## Uso: magLastModifiedFiles [-t 30min | 1w | 1m | 24h] [directorio]
## Opciones:
## <pre>
## --help | -h              Pantalla de ayuda
## --time | -t 30min | 1w | 1m | 24h
## </pre>

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

## Directorio a consultar.
dir="./"
time="24h"
find_time="-mtime 0"

## Mostrar ayuda

while [ -n "$1" ] ; do

   case "$1" in

      -t|--time) time="$2" ; shift 2 ;;
      *) dir="$1" ; break ;;

   esac

done

## Comando
## 24h
# comando_ultimos_modificados="find '$dir' -type f -mtime 0 | grep -v '.swp' | grep -v 'log/' | grep -v '.git' | sed 's/\.\///' | sed 's/^\.//'"
## 30min
# comando_ultimos_modificados="find '$dir' -type f -mmin -30 | grep -v '.swp' | grep -v 'log/' | grep -v '.git' | sed 's/\.\///' | sed 's/^\.//'"

case "$time" in
   30min) find_time="-mmin -30" ;;
   1w) find_time="-mtime -7" ;;
   1m) find_time="-mtime -30" ;;
   24h) find_time="-mtime 0" ;; # 24h
   *) help ; exit ;;
esac

comando_ultimos_modificados="find '$dir' -type f $find_time | grep -v '.swp' | grep -v 'log/' | grep -v '.git' | sed 's/\.\///' | sed 's/^\.//'"

echo Buscar en $dir con $time - $find_time
echo $comando_ultimos_modificados
echo
eval "$comando_ultimos_modificados"
