#!/bin/bash

## magUrlEncode codifica URLs, convirtiendo caracteres especiales en su
## representación segura para web, asegurando que tus enlaces funcionen
## correctamente en navegadores y servidores.
LANG=C

urlencode() {
    local l=${#1}
    for (( i = 0 ; i < l ; i++ )); do
        local c=${1:i:1}
        case "$c" in
            [a-zA-Z0-9.~_-]) printf "$c" ;;
            ' ') printf + ;;
            *) printf '%%%.2X' "'$c"
        esac
    done
}

urlencode "$@"
