#!/bin/bash

## magUrlDecode decodifica URLs codificadas, convirtiendo caracteres especiales
## de vuelta a su forma legible, útil para trabajar con enlaces web y parámetros
## de consulta.

LANG=C

urldecode() {
    local data=${1//+/ }
    printf '%b' "${data//%/\x}"
}

urldecode "$@"
