#!/bin/bash

## Abrir archivo en sesión de vim abierta.
##
## Usar: magVimRemote [archivo]
##
## En caso de no recibir el fichero a editar lo coge del porta papeles.


help() { doxygen2help "$0"; }
[[ "$1" == "-h" || "$1" == "--help" ]] && { help ; exit ; }

if [ -z "$1" ]; then
    input=`xclip -o -f`
    if [ -z "$input" ]; then
        input=`xclip -i -f`
    fi
    if [ -z "$input" ]; then
        input=`xclip -f -o -sel clip`
    fi
else
    input=$1
fi

input=`echo $input | sed 's/(/:/g' | sed 's/)//g' | sed 's/,/:/g'`
# echo "input: $input"

cmd="vim --servername vimserver --remote-send ':new $input<CR>'"

echo $cmd
eval "$cmd"

