#!/bin/bash

## magVimServer inicia Vim en modo servidor, cargando automáticamente sesiones
## guardadas para retomar tu trabajo exactamente donde lo dejaste.

help() { doxygen2help "$0"; }
[[ "$1" == "-h" || "$1" == "--help" ]] && { help ; exit ; }

if [ -f Session.vim ] ; then
    vim --servername vimserver -S Session.vim $@
else
    vim --servername vimserver $@
fi
