#!/bin/bash

if [ -z "$1" ]; then
    input=`xclip -o -f`
    if [ -z "$input" ]; then
        input=`xclip -i -f`
    fi
    if [ -z "$input" ]; then
        input=`xclip -f -o -sel clip`
    fi
else
    input=$1
fi

input=`echo $input | sed 's/(/:/g' | sed 's/)//g' | sed 's/,/:/g'`
# echo "input: $input"

cmd="vim --servername vimserver --remote-send ':new $input<CR>'"

echo $cmd
eval "$cmd"

