#!/bin/bash 

## @file evolution2csv
## 
## @brief Exportar contactos de evolution a csv
##
## Pasar todas las libretas de contactos que tenemos en evolution a un archivo csv.
##
## Esto nos permite como en mi caso abrir el documento con openoffice y controlar 
## la forma en que deseo que se impriman.
##
## nota
##   Con evolution 3.2 no funciona este script
##
## Opciones:
## <pre>
## --help | -h              Pantalla de ayuda
## </pre>
##
## Dependencias: evolution-addressbook-export
##
## @author   Eduardo Magrané
##
## @internal
##
##       web  http://www.lesolivex.com
##
##      mail  edu.lesolivex.com
##
##  Revision  SVN $Id: $
##
## Copyright  Copyright (c) 2011, Eduardo Magrané
## 
## This source code is released for free distribution under the terms of the
## GNU General Public License as published by the Free Software Foundation.

## Mostrar ayuda

function help() {

   local -i count=0
   while read linea ; do 
      let count++
      if [ $count -gt 2 ] ; then
         [ "$linea" = "" ] && return
         echo "$linea" | sed 's/^##//' | sed 's/@brief //' | sed 's/@file //' 
      fi
   done < "$0"
   echo

   }

## Pasar contactos de evolution a csv

dir_contactos="$HOME/.evolution/addressbook/local/"
fichero_final="$HOME/contactos_evolution.csv"


# Variables configurables

var_fich_conf="$HOME/.${prog}rc"
desc_var_fich_conf="Archivo de configuración"
var_color=si
desc_var_color='Presentar colores'

if [ "$1" == "--help" ] || [ "$1" == "-h" ]  ; then
   help
   exit
fi

[[ -e "$fichero_final" ]] && rm "$fichero_final"

cd "$dir_contactos"

for dir in * ; do

   evolution-addressbook-export --format=csv >> $fichero_final

done

echo Fichero generado: $fichero_final

