#!/bin/bash

## magApagar verifica el estado de tus trabajos y sesiones antes de apagar el
## ordenador, asegurándose de que no pierdas trabajo sin guardar.
##
## Apagar ordenador comprobando antes las cosas que nos interesa

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

SALIR=0

echo
echo "Mostramos estado de trabajos"
echo
magGitStatusAll
echo

# echo -n "Proyectos abiertos con ddev los cerramos..."
#
# if [[ `whereis ddev` ]] ; then
#     ddev poweroff
#    echo "Ok"
# fi

## Mirar que no tengamos alguna sesión de vim abierta

echo -n "Comprobando sesiones de vim..."

if [ "$(ps aux | grep vim | grep -v grep)" = "" ] ; then
   echo "Ok"
else
   echo "OjO"
   tput setf 4
   echo -e "Sessiones de vim abiertas"
   tput sgr0
   SALIR=1
fi

## Apagamos ordenador si todo fue bien
if [ $SALIR = 0 ] ; then

   echo
   echo "Se han encontrado incidencias, pero si no cancelas el"
   echo "apagado, continuara en 60s"
   echo
   read -t 60 -p '[ENTER] apaga ordenador / CTRL-c Cancelar' OPCION
   sudo poweroff
   # gksudo 'poweroff'

else
   echo
   read SALIR
fi
