#!/bin/bash

## magCopyTextCapture toma una captura de pantalla de una porción seleccionada y extrae el texto usando OCR, convirtiendo imágenes en texto editable.
## El texto extraído se copia al portapapeles.
##
## Basado en https://github.com/SantosRojas/text-extractor/blob/main/gstxt
##
## Dependencias: tesseract, xclip, ksnip

function show_error_dialog {
    zenity --error --text "$1"
    exit 1
}

# Tomar una captura de pantalla de una porción seleccionada de la pantalla y guardarla como un archivo de imagen
# gnome-screenshot -a -f ~/tmp/screenshot.png || show_error_dialog "Error: no se pudo tomar la captura de pantalla."
ksnip -r --saveto $HOME/tmp/screenshot.png || show_error_dialog "Error: no se pudo tomar la captura de pantalla."

# Extraer texto de la imagen utilizando Tesseract
tesseract $HOME/tmp/screenshot.png $HOME/tmp/extracted_text || show_error_dialog "Error: no se pudo extraer texto de la imagen."

# Copiar el texto extraído al portapapeles
cat $HOME/tmp/extracted_text.txt | xclip -selection clipboard || show_error_dialog "Error: no se pudo copiar el texto al portapapeles."

# Limpiar los archivos temporales
rm $HOME/tmp/screenshot.png || show_error_dialog "Error: no se pudo eliminar el archivo de captura de pantalla."
rm $HOME/tmp/extracted_text.txt || show_error_dialog "Error: no se pudo eliminar el archivo de texto extraído."
