#!/bin/bash

## magDate2time convierte fechas en formato humano a timestamps Unix, útil para
## scripting y manipulación de fechas en programas.

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

if [[ -z "$1" ]] ; then
    date +%s
else
    date --date="${1}" +%s
fi
