#!/bin/bash

## magTime2date transforma timestamps Unix en fechas legibles, facilitando la
## interpretación de tiempos en logs y bases de datos.

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi


date --date="@${1}"
