#!/bin/bash

function md2html() {

    [[ -d ~/tmp ]] || mkdir -p ~/tmp
    o=~/tmp/`basename "$1" '.md'`.html
    echo "- $1 -> $o"
    pandoc -s "$1" -o "${o}"
    xdg-open "${o}" &
}

md2html "$1"
