#!/bin/bash

CURRENT_DIR=`pwd`
SCRIPT_DIR=$( dirname -- "${BASH_SOURCE[0]}")
MARKDOWN_DIR=$( dirname -- "$1")

function md2pdf() {

    [[ -d ~/tmp ]] || mkdir -p ~/tmp
    o=~/tmp/`basename "$1" '.md'`.pdf
    # pandoc -s "$1" -o "$o"
    cd $MARKDOWN_DIR
    pandoc -s "$1" -o "$o" --template=$SCRIPT_DIR/edumag.latex --pdf-engine=xelatex -V "mainfont:DejaVu Sans" -V "monofont:DejaVu Sans Mono"
    cd $CURRENT_DIR
    xdg-open "$o" &

}

md2pdf "$@"
