#!/usr/bin/env bash

# Dependencias: libnotify-bin wget xsel zenity xclip 
#
# Gracias a Pablo Aparicio 
# http://ubunlog.com/como-traducir-cualquier-texto-en-ubuntu/

text="$(xsel -o)"
translate="$(wget -U "Mozilla/5.0" -qO - "http://translate.googleapis.com/translate_a/single?client=gtx&sl=auto&tl=es&dt=t&q=$(echo $text | sed "s/[\"'<>]//g")" | sed "s/,,,0]],,.*//g" | awk -F'"' '{print $2, $6}')"
# echo -e "Original text:" "$text"'\n' > /tmp/notitrans
# echo "Translation:" "$translate" >> /tmp/notitrans
echo "$translate" > /tmp/notitrans
echo "$translate" | xclip -selection clipboard
notify-send --icon=info "$translate"
zenity --text-info --title="Translation" --filename=/tmp/notitrans
