#!/bin/bash

## magDockerCleanAll detiene todos los contenedores Docker, elimina imágenes no
## utilizadas y limpia el sistema para liberar espacio y recursos.

docker stop $(docker ps -a -q)

docker system prune -a


