#!/bin/bash

## magLiberarMemoria optimiza el uso de memoria del sistema, liberando caché y
## buffers para mejorar el rendimiento cuando es necesario.

help() { doxygen2help "$0" ; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

sudo sync && sudo sysctl -w vm.drop_caches=3


