#!/bin/bash


if [ "$1" == "" ] ; then FILTRO='mp3' ] ; fi

for x in *
do
	if [ -d $X ] ; then 
		echo -e "<br /><a href='$x' ><h3> $x <h3></a>"

		for j in $(ls "$x/"*)
		do
			if [ "$(echo $j | cut -d. -f2)" = "jpg" ] ; then
				#echo "Fichero jpg"
				echo "<br /><img src='$j' />"
			elif [ "$(echo $j | cut -d. -f2)" = "mp3" ] ; then
				#echo "Fichero mp3"
				echo "<br /><a href='$j' > $j </a>"
			fi
		done
		
		else 
			echo "<br /><a href='$x' > $x </a>"
	fi
done

