#!/bin/bash

# Este script pasa un mp3 a wav guardandolo en el Directorio especificado
# como variable "Directorio".

# El archivo mp3 pasa como parametro al script

#directorio=/win_d/mp3/cdTemp/

echo -e "Dame el nombre que quieres ponerle al fichero(sin extension): \c"
read nombre

nombre="$nombre.wav"
echo "$nombre"
echo "$1"
mpg123 -w "$nombre" "$1"





