#!/bin/bash

## Este script automatiza la generación y visualización de un informe de
## análisis de logs de acceso web utilizando `goaccess`.  El script está diseñado
## para ejecutarse en un entorno Linux/Unix y requiere acceso a `ssh`, `scp`,
## `docker` y `xdg-open`.
##
## - Lanzar goaccess en server
## - Recoger reporte en html.
## - Mostrar reporte.

config_file="$HOME/.config/magscripts/magGoAccessInServer"
[[ -e $config_file ]] && source "$config_file"

magGoAccessInServer_dirTemp="${magGoAccessInServer_dirTemp:-$HOME/tmp/}"
magGoAccessInServer_server="${magGoAccessInServer_server:-lesolivex}"
magGoAccessInServer_logs=${magGoAccessInServer_logs:-'/var/log/nginx/lesolivex*'}

ssh $magGoAccessInServer_server "sudo cat ${magGoAccessInServer_logs} | docker run -p 7890:7890 --rm -i -e LANG=$LANG allinurl/goaccess --log-format COMBINED - > report.html"

scp ${magGoAccessInServer_server}:report.html "${magGoAccessInServer_dirTemp}report.html"

xdg-open "${magGoAccessInServer_dirTemp}report.html"
