#!/bin/bash

## magReportServer ejecuta una serie de scripts para generar un reporte
## completo del estado del servidor, incluyendo seguridad, servicios y
## rendimiento.
##
## @todo Sustituir chkrootkit por rkhunter.

help() { doxygen2help "$0"; }

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
	help
	exit
fi

echo
echo "# Report system"
echo

cd "$(dirname $0)"

for x in ./launchers/*; do
  if [ "$x" != "./launchers/whois_list" ]; then
    # echo "## $x"
    $x
  fi
done

cd -
