#!/bin/bash

## @brief Lanzador para clamscan.

help() {
    echo
    echo Lanzador para clamscan.
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## freshclam"
echo
freshclam
echo clamscan -r -i /var/
clamscan -r -i /var/
