#!/bin/bash

## @brief Mostar estado de fail2ban.

help() {
    echo
    echo Mostar estado de fail2ban.
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## Fail2Ban"

echo
echo "### fail2ban-client status"
echo

fail2ban-client status

echo
echo "### Status jails"
echo

for x in `fail2ban-client status | grep list | cut -d: -f2 | tr -d \,` ; do fail2ban-client status $x  ; done

echo
echo "### Numero de veces que se han bloqueado las IPs"
echo

zgrep -h "Ban " /var/log/fail2ban.log* | awk '{print $NF}' | sort | uniq -c | sort -nr | tee /tmp/ips_bloqueadas.txt

./whois_list /tmp/ips_bloqueadas.txt

