#!/bin/bash

## @brief Mostrar estado del firewall.

help() {
    echo
    echo Mostrar estado del firewall.
    echo
}

if [ "$1" == "-h" ] || [ "$1" == "--help" ] ; then help ; exit ; fi

echo
echo "## IPs bloqueadas"
echo

echo "### iptables -L -n --line-numbers | grep REJECT"
echo

iptables -L -n --line-numbers | grep REJECT

#  echo
#  echo "### Reglas del cortafuegos"
#  echo
#  
#  sudo iptables -L -n --line-numbers
